apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-role
  namespace: testing
subjects:
- kind: ServiceAccount
  name: test-account
#  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: my-role
  apiGroup: rbac.authorization.k8s.io

